server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]': 
            allowedOrigins: 
              - "*" 
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*" 
            allowCredentials: false 
      routes:
        - id: autorizations-service
          uri: lb://autorizations-service
          predicates:
            - Path=/api/v1/authorizations/**
        - id: categorys-service
          uri: lb://categorys-service
          predicates:
            - Path=/api/v1/categorys/**
        - id: categorys-service
          uri: lb://categorys-service
          predicates:
            - Path=/api/v1/discounts/**
        - id: categorys-service
          uri: lb://categorys-service
          predicates:
            - Path=/api/v1/employees/**
        - id: categorys-service
          uri: lb://categorys-service
          predicates:
            - Path=/api/v1/extraHours/**
        - id: categorys-service
          uri: lb://categorys-service
          predicates:
            - Path=/api/v1/latearrivals/**
        - id: categorys-service
          uri: lb://categorys-service
          predicates:
            - Path=/api/v1/paycheck/**
        - id: inandoutreg-service
          uri: lb://inandoutreg-service
          predicates:
            - Path=/api/v1/inandout/**
        - id: justifications-service
          uri: lb://justifications-service
          predicates:
            - Path=/api/v1/justifications/**
